name: CodeSniffer

on:
  push:
    branches: '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
        dependency-stability: [prefer-stable]
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.dependency-stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: cs2pr, composer

      - name: Install Composer dependencies
        run: composer install -n

      - name: Run CodeSniffer
        run: php ./vendor/bin/phpcs --no-cache --parallel=1 --report-full
